// vue-chat/src/components/UsernameInput.vue
<template>
  <div class="username-row">
    <label class="username-label">
      Nombre:
      <input
        class="text-input"
        :value="store.username"
        @input="onInput"
      />
    </label>
  </div>
</template>

<script setup lang="ts">
import { useChatStore } from '../stores/chat';

const store = useChatStore();

function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  store.setUsername(target.value);
}
</script>

// react-chat/src/components/UsernameInput.tsx
import { useChat } from '../hooks/useChat';

export function UsernameInput() {
  const { username, setUsername } = useChat();

  return (
    <div className="username-row">
      <label className="username-label">
        Nombre:
        <input
          className="text-input"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        />
      </label>
    </div>
  );
}
