// react-chat/src/components/MessageInput.tsx
import { FormEvent, useState } from 'react';
import { useChat } from '../hooks/useChat';

export function MessageInput() {
  const { sendMessage, status } = useChat();
  const [text, setText] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (!text.trim()) return;
    sendMessage(text);
    setText('');
  };

  const disabled = status !== 'connected';

  return (
    <form className="input-row" onSubmit={handleSubmit}>
      <input
        className="text-input"
        placeholder={
          disabled ? 'Conectando al servidor...' : 'Escribe un mensaje'
        }
        value={text}
        onChange={(e) => setText(e.target.value)}
        disabled={disabled}
      />
      <button className="send-button" type="submit" disabled={disabled}>
        Enviar
      </button>
    </form>
  );
}

// vue-chat/src/components/MessageInput.vue
<template>
  <form class="input-row" @submit.prevent="handleSubmit">
    <input
      class="text-input"
      :placeholder="placeholder"
      v-model="text"
      :disabled="!store.isConnected"
    />
    <button
      class="send-button"
      type="submit"
      :disabled="!store.isConnected || !text.trim()"
    >
      Enviar
    </button>
  </form>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { useChatStore } from '../stores/chat';

const store = useChatStore();
const text = ref('');

const placeholder = computed(() =>
  store.isConnected ? 'Escribe un mensaje' : 'Conectando al servidor...',
);

function handleSubmit() {
  const value = text.value.trim();
  if (!value) return;
  store.sendMessage(value);
  text.value = '';
}
</script>
